	<link rel="shortcut icon" type="image/x-icon" href="favicon.ico" />
		
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	
	<meta name="author" content="Sandra Bermudez @ bulabe.com" />
	<meta name="description" content="Humberto Ríos Rodríguez, fotógrafo. Portafolio en línea."/>
	<meta name="keywords" content="fotografía, fotógrafo, mexico foto, arte foto"/>
	
	<meta property="og:title" content="Humberto Ríos, Fotógrafo" />
	<meta property="og:type" content="website" />
	<meta property="og:description" content="Humberto Ríos Rodríguez, fotógrafo. Portafolio en línea." />
	<meta property="og:url" content="http://humbertoriosrodriguez.com" />
	<meta property="og:image" content="http://humbertoriosrodriguez.com/HRIOSFOTO.jpg" />
	
	<link rel="stylesheet" type="text/css" href="style.css" />
	
	<script type="text/javascript" src="js/jquery-1.6.2.min.js"></script>
	<script type="text/javascript" src="js/jquery.frontend.js"></script>